version: "3.8"

services:
  maya-astrology-api:
    build: .
    ports:
      - "8001:8001"
    environment:
      - PORT=8001
    restart: unless-stopped
    container_name: maya-astrology-api
    networks:
      - maya-network

networks:
  maya-network:
    driver: bridge
      start_period: 40s
